### We will use the notebook from multiple linear regression for sklearn

In [22]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

In [23]:
df = pd.read_csv('data/multiple_linear_regression.csv')
df

SAT   GPA  Rand 1,2,3
0   1714  2.40           1
1   1664  2.52           3
2   1760  2.54           3
3   1685  2.74           3
4   1693  2.83           2
..   ...   ...         ...
79  1936  3.71           3
80  1810  3.71           1
81  1987  3.73           3
82  1962  3.76           1
83  2050  3.81           2

[84 rows x 3 columns]

In [24]:
df.describe()

SAT        GPA  Rand 1,2,3
count    84.000000  84.000000   84.000000
mean   1845.273810   3.330238    2.059524
std     104.530661   0.271617    0.855192
min    1634.000000   2.400000    1.000000
25%    1772.000000   3.190000    1.000000
50%    1846.000000   3.380000    2.000000
75%    1934.000000   3.502500    3.000000
max    2050.000000   3.810000    3.000000

In [25]:
# Regression
x = df[['SAT', 'Rand 1,2,3']]
y = df['GPA']

In [26]:
model = LinearRegression()

In [27]:
model.fit(x,y)

LinearRegression()

In [28]:
model.coef_ # coefficient of the SAT score and coefficient of Rand 1,2,3

array([ 0.00165354, -0.00826982])

In [29]:
model.intercept_ # intercept of the model

0.29603261264909486

In [30]:
# Calculating R-squared
model.score(x,y)

0.40668119528142843

### Calculating Adjusted R-squared

There is no function for Adjusted R-squared in sklearn so we have to provide write it from scratch

Formula for Adjusted R-squared is:

$R^2_{adj.} = 1 - (1-R^2)*\frac{n-1}{n-p-1}$

In [31]:
# In the formula n is the number of observations (84 in here) and p is the number of predictors (2 in here)
x.shape

(84, 2)

In [32]:
# Adjusted R-squared
adjusted_r2 = 1 - (1-model.score(x,y))*((84-1)/(84-2-1))
adjusted_r2

0.39203134825134023

In [33]:
# We can create a function for future use:

r2 = model.score(x,y)
n = x.shape[0]
p = x.shape[1]

adjusted_r2 = 1-(1-r2)*(n-1)/(n-p-1)

In [34]:
adjusted_r2

0.39203134825134023

In [35]:
# Just as before we can see that adjusted R2 < R2 so one or more of predictors have little or no explanatory power 

## Feature selection

In [36]:
from sklearn.feature_selection import f_regression

In [37]:
f_regression(x,y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

First array is F-statistics and the second array is corresponding p-values

#### We are only interested in p-values so we can separate them

In [38]:
p_values = f_regression(x,y)[1]
p_values

array([7.19951844e-11, 6.76291372e-01])

In [39]:
# We can round those values to 3 digits
p_values.round(3)

array([0.   , 0.676])

 First one is p-value for 'SAT' and second one is fo 'Rand 1,2,3' so we can see one more time that 'SAT' is useful variable while 'Rand 1,2,3' isn't

### These are the univariate p-values from simple linear models; they do not reflect the interconnection of the features in multiple linear regression 

### Summary table

In [46]:
model_summary = pd.DataFrame(data= x.columns.values, columns=['Features'])
model_summary

Features
0         SAT
1  Rand 1,2,3

In [47]:
model_summary['Coefficients'] = model.coef_
model_summary['p-values'] = p_values.round(3)
model_summary

Features  Coefficients  p-values
0         SAT      0.001654     0.000
1  Rand 1,2,3     -0.008270     0.676