In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

In [2]:
df = pd.read_csv('data/simple_linear_regression.csv')
df

SAT   GPA
0   1714  2.40
1   1664  2.52
2   1760  2.54
3   1685  2.74
4   1693  2.83
..   ...   ...
79  1936  3.71
80  1810  3.71
81  1987  3.73
82  1962  3.76
83  2050  3.81

[84 rows x 2 columns]

In [3]:
x = df['SAT']
y = df['GPA']

In [4]:
x.shape, y.shape

((84,), (84,))

In [7]:
# Reshaping to the 2D array (require by sklearn) - only in simple linear regression (in multiple l.r. we don't have this issue)
x = x.values.reshape(-1,1) #we could do the same by giving exact length: reshape(84,1) but using (-1,1) we don't need to do this
x.shape

(84, 1)

In [5]:
model = LinearRegression()

In [8]:
model.fit(x,y)

LinearRegression()

In [9]:
# R-suqared
model.score(x,y)

0.40600391479679765

In [11]:
# Coefficients
model.coef_

array([0.00165569])

In [25]:
# Intercept
model.intercept_

0.2750402996602803

In [26]:
# Predicting new values
model.predict([[1740]])

array([3.15593751])

In [28]:
# Predicting with the whole df
new_data = pd.DataFrame(data=[1740,1760], columns=['SAT'])
new_data

SAT
0  1740
1  1760

In [29]:
model.predict(new_data)

array([3.15593751, 3.18905127])

In [30]:
new_data['Predicted GPA'] = model.predict(new_data)
new_data

SAT  Predicted GPA
0  1740       3.155938
1  1760       3.189051