In [1]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

### Data (generated)

In [2]:
observations = 1000

xs = np.random.uniform(low=-10, high=10, size=(observations,1))
zs = np.random.uniform(-10, 10, (observations,1))

generated_inputs = np.column_stack((xs,zs)) #it stacks data into matrix shape
noise = np.random.uniform(-1,1, (observations,1))
generated_targets = 2*xs - 3*zs + 5 + noise

np.savez('TF_intro', inputs = generated_inputs, targets = generated_targets)

In [3]:
training_data = np.load('TF_intro.npz')

In [4]:
input_size = 2
output_size = 1

model = tf.keras.Sequential([tf.keras.layers.Dense(output_size)])

model.compile(optimizer='sgd', loss='mean_squared_error')

model.fit(training_data['inputs'], training_data['targets'], epochs=100, verbose=2)

Epoch 1/100
32/32 - 0s - loss: 21.0860
Epoch 2/100
32/32 - 0s - loss: 4.6282
Epoch 3/100
32/32 - 0s - loss: 1.4913
Epoch 4/100
32/32 - 0s - loss: 0.6756
Epoch 5/100
32/32 - 0s - loss: 0.4348
Epoch 6/100
32/32 - 0s - loss: 0.3855
Epoch 7/100
32/32 - 0s - loss: 0.3621
Epoch 8/100
32/32 - 0s - loss: 0.3560
Epoch 9/100
32/32 - 0s - loss: 0.3599
Epoch 10/100
32/32 - 0s - loss: 0.3555
Epoch 11/100
32/32 - 0s - loss: 0.3602
Epoch 12/100
32/32 - 0s - loss: 0.3628
Epoch 13/100
32/32 - 0s - loss: 0.3538
Epoch 14/100
32/32 - 0s - loss: 0.3539
Epoch 15/100
32/32 - 0s - loss: 0.3546
Epoch 16/100
32/32 - 0s - loss: 0.3581
Epoch 17/100
32/32 - 0s - loss: 0.3561
Epoch 18/100
32/32 - 0s - loss: 0.3581
Epoch 19/100
32/32 - 0s - loss: 0.3575
Epoch 20/100
32/32 - 0s - loss: 0.3595
Epoch 21/100
32/32 - 0s - loss: 0.3668
Epoch 22/100
32/32 - 0s - loss: 0.3531
Epoch 23/100
32/32 - 0s - loss: 0.3529
Epoch 24/100
32/32 - 0s - loss: 0.3534
Epoch 25/100
32/32 - 0s - loss: 0.3528
Epoch 26/100
32/32 - 0s - loss: 0

### Weights and bias

In [5]:
model.layers[0].get_weights()

[array([[ 1.9647377],
        [-3.010387 ]], dtype=float32),
 array([5.0183682], dtype=float32)]

In [6]:
weights = model.layers[0].get_weights()[0]
weights

array([[ 1.9647377],
       [-3.010387 ]], dtype=float32)

In [7]:
bias = model.layers[0].get_weights()[1]
bias

array([5.0183682], dtype=float32)

### Outputs (predictions)

In [8]:
model.predict_on_batch(training_data['inputs'])

array([[ 3.25987129e+01],
       [-2.48218212e+01],
       [-1.76724281e+01],
       [-5.84685755e+00],
       [-2.46021652e+01],
       [ 1.03443146e+01],
       [ 5.55151033e+00],
       [ 1.83563099e+01],
       [ 5.62793016e+00],
       [ 4.47753906e+01],
       [ 3.56343079e+01],
       [-1.61819019e+01],
       [-2.79671555e+01],
       [-1.89661236e+01],
       [-2.98575287e+01],
       [-1.83460855e+00],
       [-1.65349178e+01],
       [ 1.48275318e+01],
       [ 1.89128399e-01],
       [ 2.68134155e+01],
       [ 4.32275238e+01],
       [ 1.64670506e+01],
       [-2.18966770e+01],
       [-3.89795160e+00],
       [ 7.82778883e+00],
       [ 3.05786514e+01],
       [ 8.04771614e+00],
       [ 8.49685860e+00],
       [ 2.31743355e+01],
       [ 3.55544815e+01],
       [ 8.70569038e+00],
       [ 1.71742764e+01],
       [-3.27475700e+01],
       [ 2.08137493e+01],
       [-1.73759518e+01],
       [ 1.43092155e+01],
       [ 3.03720341e+01],
       [-3.52058182e+01],
       [ 2.6

In [9]:
 training_data['targets'].round(1)

array([[ 31.9],
       [-24.2],
       [-17. ],
       [ -6.2],
       [-24. ],
       [  9.3],
       [  4.3],
       [ 18.5],
       [  5.8],
       [ 45.8],
       [ 35.9],
       [-15.7],
       [-28.7],
       [-17.9],
       [-29.5],
       [ -1.4],
       [-15.5],
       [ 14.6],
       [  0.9],
       [ 26.5],
       [ 43.3],
       [ 16.1],
       [-22.9],
       [ -3.1],
       [  7.6],
       [ 30.9],
       [  7.6],
       [  7.6],
       [ 22.7],
       [ 35.6],
       [  8. ],
       [ 17. ],
       [-32.9],
       [ 20.2],
       [-17.3],
       [ 13.5],
       [ 31.4],
       [-35.3],
       [  3.7],
       [ 17.2],
       [  3.9],
       [-25.9],
       [ 17.2],
       [  6.2],
       [-35.3],
       [-23.1],
       [ -4.1],
       [ -7.1],
       [  1.6],
       [-12.6],
       [ 10. ],
       [ 25.1],
       [ -5.1],
       [  8.7],
       [ 18.3],
       [ 33.7],
       [ 26.4],
       [ 38.3],
       [-22.6],
       [-15.1],
       [ 17.3],
       [  6.4],
       [