In [1]:
import numpy as np

### Transposing

In [2]:
A = np.array([[5,12,6],[-3,0,14]])
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [3]:
A.T

array([[ 5, -3],
       [12,  0],
       [ 6, 14]])

In Python a 1D arrays don't get transposed

In [14]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [15]:
x.shape

(3,)

In [16]:
x.T

array([1, 2, 3])

In [17]:
x.shape

(3,)

If reshaped into 1,3 array it can be transposed

In [12]:
x_reshaped = x.reshape(1,3)
x_reshaped

array([[1, 2, 3]])

In [13]:
x_reshaped.shape

(1, 3)

In [8]:
x_reshaped.T

array([[1],
       [2],
       [3]])