In [1]:
import numpy as np

### Addition and subtraction can be done only with matrices with the same shape. One exception (in Python) is addtion with scalar

### Addition

In [2]:
m1 = np.array([[5,12,6],[-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [3]:
m2 = np.array([[9,8,7],[1,3,-5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [4]:
m1 + m2

array([[14, 20, 13],
       [-2,  3,  9]])

### Subtraction

In [5]:
m1 - m2

array([[-4,  4, -1],
       [-4, -3, 19]])

## Addition and subtracion of vectors

In [6]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([5,4,3,2,1])

In [7]:
v1 + v2

array([6, 6, 6, 6, 6])

In [8]:
v1 - v2

array([-4, -2,  0,  2,  4])

### Addition with scalar

#### Scalar is added elementwise both to the matrix and vector

In [9]:
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [10]:
m1 + 1

array([[ 6, 13,  7],
       [-2,  1, 15]])

In [11]:
v1

array([1, 2, 3, 4, 5])

In [12]:
v1 + 1

array([2, 3, 4, 5, 6])