In [1]:
import numpy as np

### Dot product

In [2]:
x = np.array([2,8,-4])
y = np.array([1,-7,3])

In [3]:
np.dot(x,y) #2*1 + 8*(-7) + (-4)*3

-66

### Matrices multiplication

#### When multiplying matrices the second dimension in the 1st matrix (mxn) has to match first dimension in the 2nd matrix (nxk). The result of multiplication is matrix with the dimension mxk
#### For example we can multiply matrices: 2x3 and 3x4, 2x3 and 3x6, 2x3 and 3x123 ... and so on

In [5]:
A = np.array([[5,12,6],[-3,0,14]])
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [6]:
B = np.array([[2,-1],[8,0],[3,0]])
B

array([[ 2, -1],
       [ 8,  0],
       [ 3,  0]])

In [7]:
np.dot(A,B) 
# 5*2 + 12*8 + 6*3 = 124 
# 5*-1 + 12*0 + 6*0 = -5
# -3*2 + 0*8 + 14*3 = 36
# -3*-1 + 0*0 + 14*0 = 3

array([[124,  -5],
       [ 36,   3]])