### Declaring scalars, vectors and matrices

In [4]:
import numpy as np

### Scalars

In [1]:
s = 5

In [2]:
s

5

### Vectors

In [5]:
v = np.array([5,-2,4])

In [6]:
v

array([ 5, -2,  4])

### Matrices

In [10]:
m = np.array([[5,12,6],[-3,0,14]])

In [11]:
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

### Data types

In [12]:
type(s)

int

In [13]:
type(v)

numpy.ndarray

In [14]:
type(m)

numpy.ndarray

In [15]:
s_array = np.array(5)

In [16]:
s_array

array(5)

In [17]:
type(s_array)

numpy.ndarray

### Data shapes

In [21]:
s.shape

AttributeError: 'int' object has no attribute 'shape'

In [22]:
v.shape

(3,)

In [23]:
m.shape

(2, 3)

In [24]:
s_array.shape

()

## Tensors

### Creating a tensor

In [25]:
m1 = np.array([[5,12,6],[-3,0,14]])
m1

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [26]:
m2 = np.array([[9,8,7],[1,3,-5]])
m2

array([[ 9,  8,  7],
       [ 1,  3, -5]])

In [27]:
t = np.array([m1,m2])
t

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

### Checking the shape

In [28]:
t.shape

(2, 2, 3)

### Creating tensor manually

In [30]:
t_man = np.array([[[5,12,6],[-3,0,14]],[[9,8,7],[1,3,-5]]])
t_man

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])